name: Unit tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up mysql docker coontainer
      run: |
         docker rm -f mysql || true 
         docker pull mysql/mysql-server:5.6
         docker run -p 3307:3306 --name mysql -e MYSQL_ROOT_PASSWORD=leonardo-test -e MYSQL_USER=leonardo-test -e MYSQL_PASSWORD=leonardo-test -e MYSQL_DATABASE=leotestdb -d mysql/mysql-server:5.6
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run scalafmt
      env: 
        JAVA_OPTS: -Xmx3G
        JVM_OPTS:  -Xmx3G
      run: sbt -Denv.type=test clean "test:compile" scalafmtCheckAll
       
    - name: Run tests
      env: 
        JAVA_OPTS: -Xmx3G
        JVM_OPTS:  -Xmx3G
      run: |
          sbt -Denv.type=test -Dmysql.host=localhost -Dmysql.port=3307 "project http" coverage test coverageReport
          sbt -Denv.type=test "project core" coverage test coverageReport
